language: java

dist: bionic

if: |
  repo != jenkinsci/shortcut-job-plugin OR \
  type = pull_request OR \
  branch = master
services:
  - docker

cache:
  directories:
    - $HOME/.m2

jdk: openjdk11

install: skip

script:
  - |
    mvn -Pjacoco clean verify -B -V \
      -Daccess-modifier-checker.failOnError=true \
      --no-transfer-progress

#after_success:
#  - bash <(curl -s https://codecov.io/bash) -f "*jacoco.xml"

notifications:
  email: false
